version: "3"

services:
  schd-proxy:
    container_name: schd-proxy
    image: nginx:1.24.0
    restart: always
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "80:80"
      - "443:443"

  schd-backend:
    container_name: schd-backend
    image: node:20
    build: 
      context: ./backend
    restart: always
    command:
      ["sh", "-c", "npm install && npm start"]
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - ./.env

  schd-database:
    container_name: schd-database
    image: mongo:4.2.24-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ADMIN_USERPASS}
      - MONGO_INITDB_DATABASE=schedule_track
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - schd-database:/data/db

  schd-database_manager:
    container_name: schd-database_manager
    image: mongo-express
    restart: always
    ports:
      - 9081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${DB_ADMIN_USERNAME}:${DB_ADMIN_USERPASS}@schd-database:27017/?authSource=admin

volumes:
  schd-database:

networks:
  default: